### ISSUE TITLE
rpn-siganture error

### ISSUE THREAD

**Issue by spisakt** [pni-lab/PUMI#134]
rpn-signature.py seems to run on the v0.2 docker but runs oin this error:
![image](https://user-images.githubusercontent.com/21124251/208430002-c13674b5-9160-40c1-9bac-423f24a7bc9a.png)

Plus: at line 100: I had to temporarily put in a hardcoded path as the path loading mechanism didn't work inside of teh container.
We need a robust way to get the project root.

**Comment by spisakt** [comment]
I think we have definitions.py to get the root dir. However, definitions.py should be inside the PUMI module, I guess.

**Comment by khoffschlag** [comment]
fixed by "Implement BidsApp-prototype & update Dockerfile #140"
