### ISSUE TITLE
rpn_signature_timeseries_.py creates unwanted folders in the derivatives folder

### ISSUE THREAD

**Issue by khoffschlag** [pni-lab/PUMI#147]
The derivatives folder should only contain sub-xxx folders and a qc folder

![Bildschirmfoto vom 2023-02-17 16-38-24](https://user-images.githubusercontent.com/72939508/219698760-5d4fdad0-a53a-4f53-bd91-d3fcd1018603.png)

**Comment by spisakt** [comment]
Atlas related sub-workflows are not subject specific but representative for the whole pipeline.
We need to change the regexp in the decorator so that it puts all @grouppipeline derivatives into a single folder.

e.g.
group/atlas-<atlas-name>.nii.gz.    # swap '_' to '-' to be more bids-like
